### ISSUE TITLE
Call summary bot - not working

### ISSUE THREAD

**Issue by mSys-mislav** [nextcloud/call_summary_bot#37]
Hello. We've a latest version of NC 27.1.5 and Call summary bot 1.0.1 - however there is no summary after call has ended. Also there is no summary about attendees nor actions upon task: / todo: markdowns. Are we doing something wrong? Call summary is enabled in both admin part as well as in the conversation settings. 

Any hints?

**Comment by nickvergessen** [comment]
In most such cases the call was too short, default min length is 60 seconds iirc.

**Comment by mSys-mislav** [comment]
Hello! We had multiple calls that had conversations longer than 60sec.

**Comment by nickvergessen** [comment]
Then the other clue is you changed the domain/setup of the server?

**Comment by mSys-mislav** [comment]
It's standard NC installation, nothing special.

**Comment by nickvergessen** [comment]
1. Can you check with `occ talk:bot:list` if the bot is registered correctly? (okay to post the result)

2. ⚠️ Do not post those results of this question publicly ⚠️  Can you confirm that the secret from `occ talk:bot:list -vvv` is listed in `occ call-summary-bot:list` and that links correctly back to your instance in "backend"

**Comment by mSys-mislav** [comment]
1. Here it is:
`+----+-----------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------+-------+-------------------+
| id | name                  | description                                                                                                                                                                                     | error_count | state | features          |
+----+-----------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------+-------+-------------------+
| 17 | Call summary          | Call summary (British English) - The call summary bot posts an overview message after the call listing all participants and outlining tasks                                                     | 0           | 1     | webhook, response |
| 18 | Protokoll             | Protokoll (Deutsch (Persönlich: Du)) - Der Anruf-Zusammenfassungs-Bot veröffentlicht nach der Unterhaltung eine Übersichtsnachricht, in der alle Teilnehmenden und die Aufgaben aufgeführt sind | 0           | 1     | webhook, response |
| 19 | Resumen de la llamada | Resumen de la llamada (Español (España)) - El bot de resumen de llamada publica un mensaje de visión general listando a todos los participantes y delineando tareas                             | 0           | 1     | webhook, response |
| 20 | Résumé de l'appel     | Résumé de l'appel (Français) - Le robot chargé de résumer l'appel publie un message de synthèse après l'appel, énumérant tous les participants et décrivant les tâches à accomplir.             | 0           | 1     | webhook, response |
| 21 | ملخص المكالمة         | ملخص المكالمة (اللغة العربية) - يقوم روبوت "ملخص المكالمة"بنشر رسالة عامة بعد المكالمة يسرد فيها جميع المشاركين و يحدد المهام                                                                   | 0           | 1     | webhook, response |
| 22 | Resumo da chamada     | Resumo da chamada (Português Brasileiro) - O bot de resumo da chamada publica uma mensagem de visão geral após a chamada, listando todos os participantes e descrevendo as tarefas              | 0           | 1     | webhook, response |
| 23 | Çağrı özeti           | Çağrı özeti (Türkçe) - Çağrı özeti botu, çağrıdan sonra tüm katılımcıları listeleyen ve görevleri özetleyen bir özet iletisi gönderir.                                                          | 0           | 1     | webhook, response |
| 24 | 通话摘要              | 通话摘要 (简体中文) - 通话摘要机器人会在通话结束后发布一条概述信息，列出所有与会者并概述各项任务                                                                                                | 0           | 1     | webhook, response |
+----+-----------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------+-------+-------------------+
`

2. 99% of the secret is correct. 
Lets say that the following command: `occ talk:bot:list -vvv` outputs
xxxxxxxxxxxxxxxxxxxxxxxxxxxBB

I can see in the following command `occ call-summary-bot:list` output:
xxxxxxxxxxxxxxxxxxxxxxxxxxx

There are either two characters missing or the output is maybe not that long.

**Comment by nickvergessen** [comment]
Just for the record, I will still reply. Just having a huge backlog after the xmas period now and this is kind of my private/hobby project, so can't prioritize it during work hours

**Comment by mSys-mislav** [comment]
Hi @nickvergessen 
Please let me know if there are some news. Thank you.

**Comment by nickvergessen** [comment]
> 2. 99% of the secret is correct.
> Lets say that the following command: occ talk:bot:list -vvv outputs
> xxxxxxxxxxxxxxxxxxxxxxxxxxxBB
> 
> I can see in the following command occ call-summary-bot:list output:
> xxxxxxxxxxxxxxxxxxxxxxxxxxx

That is the correct behaviour,.

Do the backend from `call-summary-bot:list` and the url from `talk:bot:list -v` also match?
Local examples:
```sh
occ call-summary-bot:list
+------------------------------------------+------------------------------------------------------------------+----------------------------+
| id                                       | secret                                                           | backend                    |
+------------------------------------------+------------------------------------------------------------------+----------------------------+
| acbb798ffb8a28117e22a7be94437785922c9501 | Nnp9oTffqpPowBsgkaafCGkdXszcYt8Pjkp2Y9nfxi5P4eHo8J2z4BR98nk7Qo6R | https://nextcloud29.local/ |
+------------------------------------------+------------------------------------------------------------------+----------------------------+
```

```sh
occ talk:bot:list -v
+----+-----------------------+-----------------------------------------------------------------------------+------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------+-------------+-----------------+--------------------+-------+-------------------+
| id | name                  | url                                                                         | url_hash                                 | description                                                                                                                                                                                     | secret                                                               | error_count | last_error_date | last_error_message | state | features          |
+----+-----------------------+-----------------------------------------------------------------------------+------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------+-------------+-----------------+--------------------+-------+-------------------+
| 42 | Call summary          | https://nextcloud29.local/ocs/v2.php/apps/call_summary_bot/api/v1/bot/en    | 160948bf5454b23f5203d7c7d4106aaacfd9bf79 | Call summary (British English) - The call summary bot posts an overview message after the call listing all participants and outlining tasks                                                     | Nnp9oTffqpPowBsgkaafCGkdXszcYt8Pjkp2Y9nfxi5P4eHo8J2z4BR98nk7Qo6Ren   | 0           | 0               |                    | 1     | webhook, response |
+----+-----------------------+-----------------------------------------------------------------------------+------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------+-------------+-----------------+--------------------+-------+-------------------+
```

**Comment by mSys-mislav** [comment]
Yes, correct, they do match.

**Comment by nickvergessen** [comment]
Do you see the `👍` reaction on todo items when you post them during a call?
Or does your nextcloud.log file create an error while doing that??

**Comment by nickvergessen** [comment]
CLosing due to missing feedback

**Comment by mSys-mislav** [comment]
Hello. Sorry. There is no reaction on todoitem.
I'll check the logs and get back to you tomorrow.

**Comment by mSys-mislav** [comment]
We tried having multiple calls 10-15mins in length, no difference.
There are no errors in the nextcloud.log file.
There is no 👍 reaction on todo items when we post them during a call.

How can we debug this further?

**Comment by hartsberger** [comment]
We have the same issue. 
Nextcloud version: 27.1.9
Call summary bot version: 1.1.0

```
occ talk:bot:list
+----+-----------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------+-------+-------------------+
| id | name      | description                                                                                                                                                                                     | error_count | state | features          |
+----+-----------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------+-------+-------------------+
| 10 | Protokoll | Protokoll (Deutsch (Persönlich: Du)) - Der Anruf-Zusammenfassungs-Bot veröffentlicht nach der Unterhaltung eine Übersichtsnachricht, in der alle Teilnehmenden und die Aufgaben aufgeführt sind | 0           | 1     | webhook, response |
+----+-----------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------+-------+-------------------+
```

Backend is OK
secret is OK

Tested with 1on1 calls as well as group calls. 
Bot is activated on these calls. 
Calls were longer than 1 minute. 
No messages in Nextcloud logfile. 

There is no reaction on any "task: ..." or "todo: ..." message. 
No summary is generated. 

See the chat: 

![2024-05-22 11_32_57-Window](https://github.com/nextcloud/call_summary_bot/assets/60740965/8c69a33b-e711-4c7f-863f-d00dbf4225ee)

How can we help to troubleshoot this?

**Comment by nickvergessen** [comment]
Maybe you can check the log level for some time to info/debug or add:
```php
'log.condition' => [
	'apps' => ['call_summary_bot'],
],
```

**Comment by nickvergessen** [comment]
Another thing you could check is: are there any requests to the bot in your webserver access log.
With default apache2 the command would be something like:

```
 grep 'call_summary_bot' /var/log/apache2/access.log
::1 - - [06/Jun/2024:11:05:48 +0200] "POST /ocs/v2.php/apps/call_summary_bot/api/v1/bot/en HTTP/1.1" 200 3545 "-" "Nextcloud Server Crawler"
::1 - - [06/Jun/2024:11:05:55 +0200] "POST /ocs/v2.php/apps/call_summary_bot/api/v1/bot/en HTTP/1.1" 200 3549 "-" "Nextcloud Server Crawler"
::1 - - [06/Jun/2024:11:05:59 +0200] "POST /ocs/v2.php/apps/call_summary_bot/api/v1/bot/en HTTP/1.1" 200 3551 "-" "Nextcloud Server Crawler"
::1 - - [06/Jun/2024:11:06:00 +0200] "POST /ocs/v2.php/apps/call_summary_bot/api/v1/bot/en HTTP/1.1" 200 3553 "-" "Nextcloud Server Crawler"
```

An additional thing would be:
Are you using self-signed certificates?

**Comment by hartsberger** [comment]
@nickvergessen, thanks for the hint how to enable debugging. 

I found the error with log level = 1 in nextcloud.log
`OCP\\Http\\Client\\LocalServerException: Host violates local access rules`

After a quick research I found a solution. Add the following line to the config.php: 
`  'allow_local_remote_servers' => true,`

[Reference to Nextcloud documentation](https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/config_sample_php_parameters.html#allow-local-remote-servers)

[Here is a bit of explanation on what this parameter does](https://help.nextcloud.com/t/what-does-allow-local-remote-servers-do/188618)


**But to be honest I am not sure why this is needed anyway.**
As mentioned in the Nextcloud Forum (see link above) some apps, that rely on such a function could implement that directly. 

**It seems to me that this is the case for this app. Is it possible to fix this in the app?**
Or is there a misconfiguration on our site?

@mSys-mislav, can you check if this is working for you with this parameter?
For me it does for now 🙂

Thanks.

**Comment by nickvergessen** [comment]
You should not set this parameter or have to set it.
The Talk BotService is setting the same option for it's own requests already:
https://github.com/nextcloud/spreed/blob/1ccbf67da231c37801c1406b10000144125aec35/lib/Service/BotService.php#L159-L161

But maybe something is missing in that path. Can you share the full log line with me?

**Comment by nickvergessen** [comment]
Oh, what a fail. The response side is failing.
I will add the option to the requests the call_summary_bot sends as well. Then it should work.

**Comment by nickvergessen** [comment]
Mind to test this patch? https://github.com/nextcloud/call_summary_bot/pull/68

See https://docs.nextcloud.com/server/latest/admin_manual/issues/applying_patch.html for a quick manual how to apply a patch.

If not it's also okay and I will just release a new version later today.

**Comment by nickvergessen** [comment]
v1.1.1 is available in the app store now

**Comment by hartsberger** [comment]
Now it's working without the parameter. Thanks

**Comment by mSys-mislav** [comment]
On my end it's still not working, even with allow_local_remote_servers set to true OR upgrade to 1.1.1.

**Comment by hartsberger** [comment]
1. Do you see any errors when enabling debug logging like described here?

> Maybe you can check the log level for some time to info/debug or add the following log condition to your `config/config.php`:
> 
> ```
> 'log.condition' => [
> 	'apps' => ['call_summary_bot'],
> ],
> ```
> 
> Then there should be more logs

2. Are there errors in the access.log file as mentioned here: 


> Another thing you could check is: are there any requests to the bot in your webserver access log. With default apache2 the command would be something like:
> 
> ```
>  grep 'call_summary_bot' /var/log/apache2/access.log
> ::1 - - [06/Jun/2024:11:05:48 +0200] "POST /ocs/v2.php/apps/call_summary_bot/api/v1/bot/en HTTP/1.1" 200 3545 "-" "Nextcloud Server Crawler"
> ::1 - - [06/Jun/2024:11:05:55 +0200] "POST /ocs/v2.php/apps/call_summary_bot/api/v1/bot/en HTTP/1.1" 200 3549 "-" "Nextcloud Server Crawler"
> ::1 - - [06/Jun/2024:11:05:59 +0200] "POST /ocs/v2.php/apps/call_summary_bot/api/v1/bot/en HTTP/1.1" 200 3551 "-" "Nextcloud Server Crawler"
> ::1 - - [06/Jun/2024:11:06:00 +0200] "POST /ocs/v2.php/apps/call_summary_bot/api/v1/bot/en HTTP/1.1" 200 3553 "-" "Nextcloud Server Crawler"
> ```
> 
> An additional thing would be: Are you using self-signed certificates?

**Comment by mSys-mislav** [comment]
Self-signed certificates are not used - only purchased ones or LetsEncrypt.
I wasn't able to find anything in the logs.
There is no call_summary_bot in the logs.

Could it be related to the version on the NC? 27.1.x is used.

**Comment by nickvergessen** [comment]
> Just to confirm, it should register anything that starts with:

Yeah, but the bot will be invoked with any chat message, so if you don't see a request in the access log, either the bot is not installed, or not enabled in the conversation you are trying.

**Comment by mSys-mislav** [comment]
How can I enable the bot in the conversations?
I can see it in the admin gui, listed, I also get output from call-summary-bot:list and talk:bot:list (and URL match)

**Comment by hartsberger** [comment]
Talk --> Conversationsettings --> Bots --> Enable bot

**Comment by mSys-mislav** [comment]
It works now. It was disabled the whole time. 
It was not clear from the documentation that this has to be enabled in that specific place. I suggest you add it to the FAQ, might be easier for the others in the future.
Many thanks for the help, I appreciate it.
