### ISSUE TITLE
Can't Remove Call Bot after server migration

### ISSUE THREAD

**Issue by reidellawfirm** [nextcloud/call_summary_bot#38]
I recently submitted an issue (#30  ) where my call summary bot was not working. The issue was closed after some bug was identified but the fix did not help me and I am trying to completely remove the call summary bot from my server so I can try to reinstall it fresh. 

I am attaching various screencaps showing my current status. Please let me know what steps I can take to troubleshoot this and hopefully reinstall the bot fresh.

Screencap 1: showing the call summary bot is not installed per NC Apps
![Screenshot from 2023-12-28 17-17-00](https://github.com/nextcloud/call_summary_bot/assets/75231847/6a629e46-5674-49b9-9861-a24eecef6788)

Screencap 2: showing the talk bot list per OCC, bot sure if it matters but note the bots go from 1-8 and then repeat starting at 17
![Screenshot from 2023-12-28 17-16-22](https://github.com/nextcloud/call_summary_bot/assets/75231847/39d7dc00-a506-4aee-9e7a-4871317b3420)

Screencap 3: showing the talk bot list details per OCC; note that the first set of bots are for an older server (signal.) which existed before a migration; the current server is cloud.; 
![Screenshot from 2023-12-28 17-18-08](https://github.com/nextcloud/call_summary_bot/assets/75231847/2c1a1335-d5e9-4462-b8b1-8a8fadb9dddd)

Screencap 4: detailed lost continued
![Screenshot from 2023-12-28 17-18-13](https://github.com/nextcloud/call_summary_bot/assets/75231847/d36537e4-b8f7-4585-9c7b-69a1c370a292)

Screencap 5: call summary bot commands not recognized in OCC
![Screenshot from 2023-12-28 17-19-19](https://github.com/nextcloud/call_summary_bot/assets/75231847/18566bb4-9c2a-4aed-810d-5e9bc13544d1)

**Comment by nickvergessen** [comment]
We can just continue over there. Just thought it would solve it.
