### ISSUE TITLE
I can't work out the correct syntax for posting mutiple tasks at once

### ISSUE THREAD

**Issue by jdaviescoates** [nextcloud/call_summary_bot#40]
I've tried e.g.

```
todo:

task 1 @username  
task 2   @username 
task 3   @username
```

But that just got summarised as one task

And I tried:

```
Some more tasks:

todo: task 1 @jdaviescoates 
todo: task 2 @jdaviescoates
```

But those weren't picked up at all.

Perhaps you could simply add an example bit of text to the the README?

**Comment by nickvergessen** [comment]
each line needs to have the keyword as per readme, so

```
todo: task 1 @username  
todo: task 2   @username 
todo: task 3   @username
```

should work and it does in my test:

![image](https://github.com/nextcloud/call_summary_bot/assets/213943/47859e45-1029-4029-af0d-05485268844a)
