### ISSUE TITLE
Feature Request: Allow to tag additional notes and decisions for summary in different sections of the protocol

### ISSUE THREAD

**Issue by lars-becker** [nextcloud/call_summary_bot#53]
We started using this useful bot in video conferences and it really makes it easy prototyping a meeting protocol. Currently we prefix every line with "todo:"  even if we want to note something. Then we reorganize it afterwards. In many meetings not only the tasks need to be noted, but also *decisions* that where made or *additional notes*, that are important for those who could not attend or us to remember.

It would be super nice if the key words "decision:" and "note:" could be added automatically to such sections in the protocol. Maybe also a "report:" prefix for important reports. All of course with bullet points instead of checkboxes.

**Comment by nickvergessen** [comment]
As I just implemented "agenda" #83  I was thinking about this again.
Do you think it's okay to require sending todo in different messages then decision/note/report?
Otherwise the regex handling might turn quite complex for now
