### ISSUE TITLE
Call summary bot is using timezone UTC

### ISSUE THREAD

**Issue by 42ske** [nextcloud/call_summary_bot#56]
Though our server and Nextlcloud installation (including Talk) uses another timezone than UTC the call summary bot uses UTC which leads to confusing summaries. Is this a bug or ist there a possiblity to configure timezone for call summary bot?

**Comment by nickvergessen** [comment]
Unfortunately at this point the Bot system of Talk does not allow "configurations" to be stored on a conversation level.

The server code we use to display falls back to "UTC" when there is no user in context.
But I could think about adding a "global" option which could be helpful if all calls are in the same other timezone.

**Comment by hartsberger** [comment]
@nickvergessen, this would be realy helpful, because the participants would assume the correct time in a summary protocoll. 

For us, it is only 2 hours difference. But I guess that it is more annoing if you are several hours away from UTC. Then even the date wouldn't be correct.

**Comment by nickvergessen** [comment]
I could add a "quick" appconfig which can be used as a workaround but uses whatever timezone then for all calls.
Might be good for some, but e.g. doesn't work on the instance we run ourselves, as half of the people are not from CEST.

We discussed recently that we want to be "globally" able to post times in chat messages and each user sees that in their own timezone then.
That would then be the final solution.
