### ISSUE TITLE
No tasks summary after the end of the call

### ISSUE THREAD

**Issue by ibahnasy** [nextcloud/call_summary_bot#80]
Tasks were added during a call but at the end, the bot didn't show a summary of the tasks at all.

**Comment by nickvergessen** [comment]
Was there a 👍 reaction on the task message?

**Comment by ibahnasy** [comment]
No.

![image](https://github.com/user-attachments/assets/d530c5f0-5587-4fcc-8a23-002a9491e7c2)

**Comment by nickvergessen** [comment]
Did you enable it in the conversation settings before the call?
![grafik](https://github.com/user-attachments/assets/de2a7598-97ab-4cba-89e4-28d09a0f8f45)

**Comment by ibahnasy** [comment]
You are right, now it's working :) Thanks.
But does the bot performs external API calls or it run locally only?

**Comment by nickvergessen** [comment]
It runs fully on your Nextcloud server, but currently calls itself via API
